export const allCuisines = {
  'North American': [
    'Southern Soul',
    'Cajun',
    'Fast Food',
    'Midwestern',
    'Tex Mex',
    'Tlingit (Native)',
    'Mid Atlantic',
    'Canadian',
  ],
  'Central American + Caribbean': [
    'Mexican',
    'Guatemalan',
    'Costa Rican',
    'Cuban',
    'Jamaican',
    'Haitian',
    'Nicaraguan',
    'Puerto Rican',
    'Dominican',
  ],
  'South American': [
    'Brazilian',
    'Guyanese',
    'Venezuelan',
    'Peruvian',
    'Colombian',
    'Chilean',
    'Argentinian',
    'Ecuadorean',
  ],
  'Western European + Mediterranean': [
    'Portuguese',
    'Spanish',
    'French',
    'British',
    'Irish',
    'Scottish',
    'Italian',
    'Greek',
    'Croatian',
    'Albanian',
    'Belgian',
    'Australian',
  ],
  'Central + Eastern European': [
    'German',
    'Dutch',
    'Swiss',
    'Czech',
    'Polish',
    'Romanian',
    'Russian',
    'Swedish',
    'Danish',
    'Nordic',
    'Icelandic',
    'Lithuanian',
    'Ukrainian',
  ],
  'Middle Eastern': [
    'Turkish',
    'Syrian',
    'Israeli',
    'Iraqi',
    'Persian',
    'Arabian',
    'Afghani',
    'Georgian',
    'Turkmeni',
    'Armenian',
    'Kazakh',
    'Pakistani',
    'Lebanese',
  ],
  'North African': [
    'Egyptian',
    'Libyan',
    'Moroccan',
    'Tunisian',
    'Sudanese',
  ],
  'Sub-Saharan': [
    'Nigerian',
    'Gambian',
    'Ethiopian',
    'South African',
    'Kenyan',
    'Ugandan',
  ],
  'Indian/Himalayan': [
    'North Indian',
    'South Indian',
    'Gujarati',
    'Sri Lankan',
    'Nepalese',
    'Bangladeshi',
  ],
  'East Asian': [
    'Cambodian',
    'Lao',
    'Taiwanese',
    'Japanese',
    'Korean',
    'Mongolian',
  ],
  'Chinese': [
    'Sichuan',
    'Fujian',
    'Hunan',
    'Cantonese',
    'Shandong',
    'Jiangsu',
    'Hong Kong',
  ],
  'Southeast Asian/Micronesian': [
    'Malaysian',
    'Singaporean',
    'Filipino',
    'Indonesian',
    'Papua New Guinean',
    'Hawaiian',
    'Thai',
    'Vietnamese',
  ],
};

export const cuisineMap = {
  'Southern Soul': 'North American',
  'Cajun': 'North American',
  'Fast Food': 'North American',
  'Midwestern': 'North American',
  'Tex Mex': 'North American',
  'Tlingit (Native)': 'North American',
  'Mid Atlantic': 'North American',
  'Canadian': 'North American',
  'Mexican': 'Central American + Caribbean',
  'Guatemalan': 'Central American + Caribbean',
  'Costa Rican': 'Central American + Caribbean',
  'Cuban': 'Central American + Caribbean',
  'Jamaican': 'Central American + Caribbean',
  'Haitian': 'Central American + Caribbean',
  'Nicaraguan': 'Central American + Caribbean',
  'Puerto Rican': 'Central American + Caribbean',
  'Dominican': 'Central American + Caribbean',
  'Brazilian': 'South American',
  'Guyanese': 'South American',
  'Venezuelan': 'South American',
  'Peruvian': 'South American',
  'Colombian': 'South American',
  'Chilean': 'South American',
  'Argentinian': 'South American',
  'Ecuadorean': 'South American',
  'Portuguese': 'Western European + Mediterranean',
  'Spanish': 'Western European + Mediterranean',
  'French': 'Western European + Mediterranean',
  'British': 'Western European + Mediterranean',
  'Irish': 'Western European + Mediterranean',
  'Scottish': 'Western European + Mediterranean',
  'Italian': 'Western European + Mediterranean',
  'Greek': 'Western European + Mediterranean',
  'Croatian': 'Western European + Mediterranean',
  'Albanian': 'Western European + Mediterranean',
  'Belgian': 'Western European + Mediterranean',
  'Australian': 'Western European + Mediterranean',
  'German': 'Central + Eastern European',
  'Dutch': 'Central + Eastern European',
  'Swiss': 'Central + Eastern European',
  'Czech': 'Central + Eastern European',
  'Polish': 'Central + Eastern European',
  'Romanian': 'Central + Eastern European',
  'Russian': 'Central + Eastern European',
  'Swedish': 'Central + Eastern European',
  'Danish': 'Central + Eastern European',
  'Nordic': 'Central + Eastern European',
  'Icelandic': 'Central + Eastern European',
  'Lithuanian': 'Central + Eastern European',
  'Ukrainian': 'Central + Eastern European',
  'Turkish': 'Middle Eastern',
  'Syrian': 'Middle Eastern',
  'Israeli': 'Middle Eastern',
  'Iraqi': 'Middle Eastern',
  'Persian': 'Middle Eastern',
  'Arabian': 'Middle Eastern',
  'Afghani': 'Middle Eastern',
  'Georgian': 'Middle Eastern',
  'Turkmeni': 'Middle Eastern',
  'Armenian': 'Middle Eastern',
  'Kazakh': 'Middle Eastern',
  'Pakistani': 'Middle Eastern',
  'Lebanese': 'Middle Eastern',
  'Egyptian': 'North African',
  'Libyan': 'North African',
  'Moroccan': 'North African',
  'Tunisian': 'North African',
  'Sudanese': 'North African',
  'Nigerian': 'Sub-Saharan',
  'Gambian': 'Sub-Saharan',
  'Ethiopian': 'Sub-Saharan',
  'South African': 'Sub-Saharan',
  'Kenyan': 'Sub-Saharan',
  'Ugandan': 'Sub-Saharan',
  'North Indian': 'Indian/Himalayan',
  'South Indian': 'Indian/Himalayan',
  'Gujarati': 'Indian/Himalayan',
  'Sri Lankan': 'Indian/Himalayan',
  'Nepalese': 'Indian/Himalayan',
  'Bangladeshi': 'Indian/Himalayan',
  'Cambodian': 'East Asian',
  'Lao': 'East Asian',
  'Taiwanese': 'East Asian',
  'Japanese': 'East Asian',
  'Korean': 'East Asian',
  'Mongolian': 'East Asian',
  'Sichuan': 'Chinese',
  'Fujian': 'Chinese',
  'Hunan': 'Chinese',
  'Cantonese': 'Chinese',
  'Shandong': 'Chinese',
  'Jiangsu': 'Chinese',
  'Hong Kong': 'Chinese',
  'Malaysian': 'Southeast Asian/Micronesian',
  'Singaporean': 'Southeast Asian/Micronesian',
  'Filipino': 'Southeast Asian/Micronesian',
  'Indonesian': 'Southeast Asian/Micronesian',
  'Papua New Guinean': 'Southeast Asian/Micronesian',
  'Hawaiian': 'Southeast Asian/Micronesian',
  'Thai': 'Southeast Asian/Micronesian',
  'Vietnamese': 'Southeast Asian/Micronesian',
};

export const wildCards = [
  'Cold',
  'Vegan',
  'Dessert',
  'Main',
  'Side',
  'Small Bites/Finger Food',
  'Snack',
  'Drink (non-alcoholic)',
  'Drink (alcoholic)',
  'Style of First, Flavor of Second',
  'Flavor of First, Style of Second',
  'Spin for a 3rd',
  'Replace First with Your Choice',
  'Replace Second with Your Choice',
  'Replace Both with Your Choice',
  'Vegetarian',
  'Dairy free',
  'Gluten free',
  'Breakfast',
];